### ISSUE TITLE
US 7 Play-Card Win

### ISSUE THREAD

**Issue by milodevhh** [milodevhh/Capstone-Projekt-BingoApp#10]
## Value proposition

As a user, 
I want to be notified if I scored a bingo,
so that I can celebrate.

## Description

<img width="582" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/f7e99fd6-7ae1-460b-9b81-0da50849e61f">

## Acceptance criteria

There are several ways to win: When the user has clicked either vertical or horizontal a row of 3 fields - an icon is displayed to the user which is supposed to represent the game success. 

If the user has won via one of the options, a Game Restart button will appear. 

## Tasks

- [x]  create a BRANCH feat/play-win
- [x]  add a function that track the selected cards
- [x] use Math.floor to check vertical or horizontal
- [x] add a text and an SVG file to display the game success
- [x] add a function to restart the game grid
- [x] add a restart button 
- [x] add styling 

## Size
large

**Comment by ninaassmann** [comment]
very short for such a big feature, maybe you can explain more, how the function will work or how you track the cards

**Comment by F-Kirchhoff** [comment]
Hey,
this one is quite good already, please adjust the following:
- change the value proposition: As a user, I want to be notified if I scored a bingo, so that I can celebrate
- You specified that a modal will appear, but in your sketch the buttons are displayed in the flow of the Card page. Please commit to one of the options, (either change the tasks or the sketch)

**Comment by milodevhh** [comment]
Hey Felix, thanks mdn was my saviour - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/floor?retiredLocale=de

**Comment by F-Kirchhoff** [comment]
Ah, wegen den reihen / spalten? Du brauchst aber noch den % operator oder? ;)

**Comment by milodevhh** [comment]
Yes, ich habe es in der US nochmal angepasst, beschränke mich auf vertikal und horizontal...
