### ISSUE TITLE
US 6 Fetch Icon for Input 

### ISSUE THREAD

**Issue by milodevhh** [milodevhh/Capstone-Projekt-BingoApp#11]
## Value proposition

As a User,
I want to have a wide range of icons.
So that I am able to choose between different icons.

## Description

<img width="154" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/6dda08e7-5b43-4252-bf04-eca901de0913">

## Acceptance criteria

In the Navigation at the bottom of the app, the user can switch between the "Play" and "Edit" page.
The cards can be edited via the input field Icon. 
The user can choose from a large selection of icons here, in order to be able to see different topics. 

## Tasks

- [x] create a BRANCH feat/icon-api-fetch
- [x] get an auth key for the API / https://api-ninjas.com/api/emoji
- [x] use fetch to get the first 30 icons 
- [x] add useState to get an Array of the Objects 
- [x] map over the Array 
- [x] modify the input field icon in the form 

## Size

medium

**Comment by Roland-Hufnagel** [comment]
If you know it by now you can mention the API, you want to use.

**Comment by milodevhh** [comment]
Hey Roland, thanks - I will use https://api-ninjas.com/api/emoji
