### ISSUE TITLE
US 8 - Fix Styling Bug Add Typo 

### ISSUE THREAD

**Issue by milodevhh** [milodevhh/Capstone-Projekt-BingoApp#12]
## Value proposition

As a User,
I want to have more Information about the game,
so that the game quickly becomes fun.

## Description

<img width="174" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/2f02c97e-96b3-4f6f-8dfc-a43f7f597a09">

## Acceptance criteria
- About a new page, the game idea and the gameplay should be explained to the user.
- The user can access the individual pages via the nav menu, the SVGs in the nav are filled when the user is on the respective page. 

## Tasks

- [x] create new branch feat/styling
- [x] add a typo 
- [x] add a new page "Welcome", add a gif 
- [x] ad an SVG for the "Welcome" pages in the nav 
- [x] add text and styling 

## Size
medium

**Comment by JanaS87** [comment]
Looks very good so far, I just have one question: What is a "typo"? First and foremost, I associate it with a typo (Tippfehler), but that can't be it :D

👍

**Comment by milodevhh** [comment]
Hey, Typography ...I have meant  ;)
