### ISSUE TITLE
US9 Refactoring

### ISSUE THREAD

**Issue by milodevhh** [milodevhh/Capstone-Projekt-BingoApp#17]
## Value proposition

As a User,
I want to see the welcome Content at first,
In order to get a good Idea, what's the App about. 

## Description

<img width="160" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/a5d42032-a98d-465b-b5bb-8b01b55a2640">

## Acceptance criteria

The App will welcome the User with a Text and grafic. 
There will be shown a Link, "Let´s Play" - to guide users to the play page.
The other two pages /edit & /play can be reached via the NAV.

## Tasks

- [x] create new branch feat/refactoring
- [x] change pages structure 
- [x] switch function from index.js
- [x] render welcome content on index.js 
- [x] add styling 

## Size
medium
