### ISSUE TITLE
US 2 - Add Play cards (Form)   

### ISSUE THREAD

**Issue by milodevhh** [milodevhh/Capstone-Projekt-BingoApp#2]
## Value proposition  

As a User,
I want to add my own Play cards.
 So that I am to be able to make the game sustainable for my trip or use. 

 ## Description  

<img width="173" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/372b7829-9acd-4dfe-b1db-f49a1f41182e">

 

 ## Acceptance criteria 
- [x] The user have access to the Input fields, 9 Cards can be added. With the Inputs Name #xy Card & Icon. 
- [x] At the end of the Form, the user will find a Button. 
- [x] After clicking add Play cards - The User will return to the Play page and see the own 9 Play card with  
        Icons and Name 

## Tasks 
- [x] create a BRANCH feat/add-cards
- [x]  - [ ] create a new page - edit, create a component for the form 
- [x] input and label to insert the Name and Icon via <select> at first only 15 Icons to select. 
- [ ] create a component for the submit button, handle onClick 
- [ ] useState for the Play cards, an array with objects 
- [ ] router.push("/play") to get the User to “Play” 

## Size
medium

**Comment by KilianBau** [comment]
Hey Milo, I don't get what the #xy input field means, and why you need two input fields. Or do you intend the #xy as an example for the input fields 2-9? Why do you need components for the form and the buttons? I think you just need them on one page, so in my opinion it's not necessary to create components. Where do you get the 15 icons from? Please have a look at the structure of your user story and a few sentences are hard to read because of the grammar. I like your wireframe but I can see an edit button that you don't mention.

**Comment by DorisW3** [comment]
Hey Milo, 
in the third line you should write " So that I _am able to_ make...", and in the Description field please change the description of the input fields to "Choose _an_ icon" for correct grammar ;-) 
However, I think your user story is too large. You should split it into smaller ones! So that you can finish more user stories (for a better feeling;-) ) and keep the overview about what you already did and what has to be done. :-)

**Comment by milodevhh** [comment]
> Hey Milo, I don't get what the #xy input field means, and why you need two input fields. Or do you intend the #xy as an example for the input fields 2-9? Why do you need components for the form and the buttons? I think you just need them on one page, so in my opinion it's not necessary to create components. Where do you get the 15 icons from? Please have a look at the structure of your user story and a few sentences are hard to read because of the grammar. I like your wireframe but I can see an edit button that you don't mention.

Hey Kilian, thanks, I understood.  Yes there should be no second button, there is only to submit (add Playcards)

**Comment by milodevhh** [comment]
> Hey Milo, in the third line you should write " So that I _am able to_ make...", and in the Description field please change the description of the input fields to "Choose _an_ icon" for correct grammar ;-) However, I think your user story is too large. You should split it into smaller ones! So that you can finish more user stories (for a better feeling;-) ) and keep the overview about what you already did and what has to be done. :-)

Hey Doris, thanks for the good Feedback. I will cheek my grammar!!!

**Comment by milodevhh** [comment]
#US 2 - Add Game cards (Form)

  ## Value proposition  
As a User,
I want to add my own Game cards. So that I am able to make sustainable cards for my trip. 

 ## Description  





<img width="180" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/8de0d4a7-25f0-428e-953e-7701a0757300">










 


 ## Acceptance criteria 
- [ ] The user have access to the Input fields, 9 cards can be added. With the Inputs Name #numer Card & Icon.  
        only 3 fields are shown in the Description. 
- [ ] At the end of the Form, the user will find a Button. 
- [ ] After clicking the Button - The User will return to the Play page and see the own 9 Game cards with  
        Icons and Names. 

## Tasks 
- [ ] create a BRANCH feat/add-cards
- [ ] create a new page - edit, create a component for the form 
- [ ] input and label to insert the Name and Icon via select
- [ ] create a component for the submit button, handle on Click
- [ ]  useState for the Game cards  an array with objects 
- [ ] router.push("/play") to get the User to “Play”

**Comment by milodevhh** [comment]
#US 2 - Add Game cards (Form)

  ## Value proposition  
As a User,
I want to add my own Game cards. 
So that I am able to make sustainable cards for my trip. 

 ## Description  




<img width="381" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/58bc818a-b71b-48b9-a62f-df153a1bf31f">










 


 ## Acceptance criteria 
- [ ] The user have access to the Input fields, 9 cards can be added. With the Inputs Name #numer Card & Icon.  
        only 3 fields are shown in the Description. 
- [ ] At the button of the app, a nav with two Buttons will be shown. The User can click the play Game button to go to the 
       "Play" page. and the edit Button to add or latter edit the cards. 
- [ ] At the end of the Form, the user will find a Button. 
- [ ] After clicking the Button - The User will return to the Play page and see the own 9 Game cards with  
        Icons and Names. 

## Tasks 
- [ ] create a BRANCH feat/add-cards
- [ ] create a new page - edit, create a component for the form 
- [ ] add a Nav file and add first two svg for “Play” and “Edit” (empty) - filled will be shown when clicked. 
- [ ] input and label to insert the Name and Icon via select
- [ ] create a component for the submit button, handle on Click
- [ ]  useState for the Game cards  an array with objects 
- [ ] router.push("/play") to get the User to “Play”

**Comment by ninaassmann** [comment]
How does the user get to this page?

**Comment by ninaassmann** [comment]
more details about how the user gets to the different pages

**Comment by ninaassmann** [comment]
LGTM
