### ISSUE TITLE
US 3 - Edit Game cards   

### ISSUE THREAD

**Issue by milodevhh** [milodevhh/Capstone-Projekt-BingoApp#5]
#US 3 - Edit Game cards   

## Value proposition  
As a User,
I want to edit my own Game cards.
 So that I am able to edit the cards and change details. 

 ## Description            

<img width="280" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/93cd355b-2ee3-43e6-bbd0-f2daadbe7837">

 

 ## Acceptance criteria 

- On the “Edit” page the User can see the 3x3 Grid and click on each card to get to the detail Page to edit   a single card. 
- On the “Edit/detail” Page, the user can edit (update) the card (name&icon)
- The Button “save” will update the card with the new content, and will bring back the user to “Edit” Page
- The Button “go back” lead the user back to the “edit” page.

## Tasks 
- [x] create a BRANCH feat/edit-cards
- [x] Lift up the function form Card to app.js 
- [x] modify the form function as a Component - to use it on the edit/detail page
- [x] add a [id] in pages/cards 
- [x] add a SAVE Button - with push router to /edit
- [x] add a LINK to /edit

## Size
medium

**Comment by ninaassmann** [comment]
do you want to use the same form as the create card form?
I guess this would be a good practice and fill the form with the current details of the card

for this you need to make your form to a dump form and make it reusable. we did something like this in a challenge

**Comment by milodevhh** [comment]
Hey Nina, Thanks -I add the Task:  modify the form function as a Component - to use it on the edit/detail page
