### ISSUE TITLE
US 4 - Delete Game cards 

### ISSUE THREAD

**Issue by milodevhh** [milodevhh/Capstone-Projekt-BingoApp#6]
## Value proposition  
As a User,
I want to delete my own Game cards. 
So that I am able to modify my 3x3 Grid of Cards 

 ## Description              

<img width="494" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/85dc2e5c-7e25-490b-bd19-2a3936422d80">

 

 ## Acceptance criteria 

- On the “Edit” page, the User can see the 3x3 Grid and click on each card to get to the detail Page to edit a single card. 
- On the “Edit/detail” Page, the user can delete a card.
- After clicking Button “Delete” a modal will show “Are you sure” with two buttons Cancel / Delete. After clicking Delete, the Card will be deleted from the Grid. 
- The Button “go back” leads the user back to the “edit” page.

## Tasks 
- [x] create a BRANCH feat/delete-cards
- [x] add a function on the edit/detail page that delete a card 
- [x] add in the function a const answer = window.confirm
- [x] add a button for Delete 
- [x] use router.push to redirect the user to /edit 

## Size
medium

**Comment by KilianBau** [comment]
_After clicking Button “Delete” a modal will show “Are you sure” with two buttons Cancel / Delete. After clicking Delete, the Card will be deleted from the Grid. By click_ --> Do you need the last "By click"?

**Tasks** 

_add a function on the edit/detail page that delete a card_ --> I prefer to explain a bit more what happens in the function, so you have instructions for the coding 

_const answer = window.confirm_ ---> have a look at this <dialog> [element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)

Maybe you explain this _add a button as return_ a bit more, I think you mean the go back button?

**Comment by KilianBau** [comment]
_add a button as return for the function, use a Dialog element for handling Cancel / Delete option._---> take the "use a dialog..." part and replace that part with it --> _add in the function a const answer = window.confirm_

_add a button as return for the function_  --> I still don't get it, what do you mean with return for the function?

**Comment by milodevhh** [comment]
Thanks, Killian, now it is a bit shorter, should be fine by now.
