### ISSUE TITLE
US 5- Generate Bingo Grid

### ISSUE THREAD

**Issue by milodevhh** [milodevhh/Capstone-Projekt-BingoApp#7]
## Value proposition  
As a user,
I want to add my own game cards. 
So that I am able to get a "Bingo Grid" generate from all my added cards. 

 ## Description  

<img width="624" alt="image" src="https://github.com/milodevhh/Capstone-Projekt-BingoApp/assets/136480925/67846880-2ed2-4e63-ade6-5438b5dae5d3">

 

 ## Acceptance criteria 

In the Navigation at the bottom of the app, the user can switch between the "Play" and "Edit" page. 

On the "Edit" page, the user can access the form's input fields "name", "icon". A wide variety of cards can be added.
The user can submit the card data by clicking the button "Add card".

The added cards are rendered as part of the list on the "Edit" Page. 
When the user clicks the button "Create new Bingo", a new bingo grid is launched and the user is redirected to the "Play" page. 

## Tasks

- [x] create a BRANCH feat/generate-bingo-grid
- [x] add Button "Create new Bingo"
- [x] Modify the function of the State thats renders the Bingo Grid 
- [x] add a function that only 9 cards are part of the Bingo Grid 
- [x] use router.push to lead the user to the "Play" page 

## Size
large

**Comment by CJAkkuec** [comment]
> US 5- Add Game cards (Form with Title)  

You don't need to put the title into your user story itself.

**Re: Value proposition**   🔽 edited version below
> As a User,
> I want to add my own game cards
> so that I am able to put them on the grid.

From your original VP:
>suitable cards for my trip

What trip?
👁️ 👄 👁️ I see you copying ...

**Re: Acceptance criteria** 

> The user have access to the Input fields, 9 cards can be add. With the Inputs Name #numer Card & Icon. Only 3 fields are shown in the Description.

I'm not sure I even understand what you're trying to say, but this one AC includes a total of three AC: ⬇️ 
> The user can access the form's input fields "name", "card number" and "icon", and enter their data
> The user can create 9 cards total

> At the button of the app a nav with two ~~Buttons~~ links will be shown.

Do you mean "bottom"?

> At the end of the Form the user will find a Button. - “Add Cards”
> After clicking the Button - The Grid with Title will be shown under the Form on the same Page, by clicking on the Cards the > User can Edit or Delete a card on the /edit/details - pages

.... what?

I think what you're trying to say is that

> The user can submit the card data
> The new card is rendered as part of the grid

**Re: Tasks** 🔽  edited version below
 > create a branch feature/form-cards 
 > create a form component with a headline and three input fields
> implement the business logic required for the user to submit their card data when creating a new card
> make sure the new card is rendered as part of the grid

**Comment by F-Kirchhoff** [comment]
Hey Milo,
from the description / acceptance criteria its not clear to me how the user is actually adding the info. Where can the user enter this adding process? (With a link to this page I assume). What are the steps that need to be performed? 

Please add more detail to the task list, it should help you to organize your coding. Please add at least one task for each component / visual element you want to display. Right now you are missing the form component, a link to the form page, a submit button, the three input fields, and the preview component that displays the grid of cards.

**Comment by jonas8900** [comment]
with the changes, it looks good and understandable to me ! But remember, you should not have large user-storys (size)!

**Comment by milodevhh** [comment]
Hey Jonas thanks, I can only badly estimate how long I need for the function, in which it is about the limitation of 9 cards and the random playing out
